zazuko/data-cube-curation

api/lib/domain/project/createDimensionTable.spec.ts, api/lib/domain/project/createDimensionTable.ts, api/lib/domain/table/addReferenceAttribute.spec.ts, api/lib/domain/table/addReferenceAttribute.ts, api/lib/domain/table/identifierTemplate.spec.ts, api/lib/domain/table/identifierTemplate.ts, api/lib/log.ts, api/lib/read-graphs/table/index.ts, api/test/DimensionTable/Create.hydra, k8s/kustomization.yaml
=> feat: add dataCube:identifierColumn to dimension table

ui/src/api/index.ts, ui/src/api/resources/source.ts, ui/src/api/uris.ts, ui/src/components/project/SourceItem.vue, ui/src/components/project/TableItem.vue, ui/src/store/modules/attributes.ts, ui/src/store/modules/sources.ts, ui/src/types.ts
=> UI: delete sources and attributes

api/hydra/projects.ttl, api/hydra/projects/get.rq, ui/src/api/index.ts, ui/src/api/resources/project.ts, ui/src/components/project/ProjectForm.vue, ui/src/store/modules/projects.ts, ui/src/types.ts, ui/src/views/Projects.vue
This PR adds the ability to edit projects.
It also improves the project form a bit by adding a help text on the baseURI field.
Maybe also interesting: I'm moving more and more towards #55 ;)
=> Ability to edit projects

api/hydra/attributes.ttl, ui/src/components/project/ReferenceAttributeForm.vue, ui/src/components/project/TableItem.vue
Present the form as a sentence to make it (maybe) easier to understand.
This is the result of what was discussed with @ktk and @l00mi today.
It will probably cause conflicts with #166. Will fix after one of them is merged.
=> feat(ui): improve usability of "reference attribute" form

ui/package-lock.json, ui/package.json, ui/src/App.vue, ui/src/components/PropertyField.vue, ui/src/components/project/ReferenceAttributeForm.vue, ui/src/components/project/TableAdvancedForm.vue, ui/src/components/project/TableItem.vue, ui/src/components/project/ValueAttributeForm.vue, ui/src/rdf-vocabularies.ts, ui/src/store/index.ts, ui/src/store/types.ts
Improve input field for RDF properties:
- Accepts and auto-completes prefixed properties
- Shows non-prefixed version to users below field
- Sends non-prefixed version to API
Fixes #161
=> feat(ui): auto-complete RDF properties

ui/src/components/project/SourceItem.vue, ui/src/types.ts, ui/src/views/project/Sources.vue
Allows to show all columns, only the mapped ones or only the "not yet mapped" ones.
=> feat(ui): add columns filter on sources page

ui/src/components/IdentifierTemplateField.vue, ui/src/components/project/TableAdvancedForm.vue, ui/src/components/project/TableForm.vue
As for property fields, show full identifier (with project base URI) under "identifier template" field.
=> feat(ui): show full identifier under input field

ui/src/components/PrefixedURI.vue, ui/src/components/PropertyField.vue, ui/src/components/project/SourceItem.vue, ui/src/components/project/TableItem.vue
Display URIs in shrinked version with tooltip showing the absolute URI.
Also includes small UI fixes.
=> feat(ui): display shrinked URIs with tooltip

ui/src/components/IdentifierTemplateField.vue
Add validation pattern for identifier template input that checks if all the columns exist.
=> feat(ui): validate identifier template input

ui/src/components/DataTypeField.vue
=> feat(ui): sort auto-complete data types alphabetically

ui/src/components/DataTypeField.vue
=> feat(ui): highlight type params button when has values

api/lib/data-cube/project/get.ts
=> fix: return 404 when project does not exist

ui/src/components/IdentifierTemplateField.vue
Display invalid column names when possible.
Addresses part of #207
=> Improve Identifier Template validation message

api/frontend.ts
The layout fo the image files changed with #201 but I missed to update the path to where the UI application is served from
=> build: correct container paths to UI files

api/lib/data-cube/table/preview.ts, api/lib/handlers/store-source.ts, api/lib/services/csvwBuilder.ts, api/lib/services/sourceSamples.ts, packages/rdfine-csvw/Csvw.ts, packages/rdfine-csvw/index.ts
=> fix: all sources must be parsed using a specific csv dialect

ui/src/api/index.ts, ui/src/api/resources/project.ts, ui/src/api/uris.ts, ui/src/components/project/ProjectForm.vue, ui/src/router.ts, ui/src/store/modules/projects.ts, ui/src/types.ts, ui/src/views/Project.vue, ui/src/views/project/Jobs.vue, ui/src/views/project/Settings.vue
=> feat(ui): ability to trigger transform job

packages/cli/lib/s3.ts
<details>
<summary>I got a crash because the pipeline was looking for a file that didn't exist and the errors weren't very helpful in finding what the issue was.</summary>
```
2020-03-11T15:42:47.933Z barnard59:runner INFO b1_openCsvFromBucket Opening file SA_Daten_0_100_fixed.csv from S3
2020-03-11T15:42:48.015Z data-cube Error: error in pipeline step urn:pipeline:data-cube-curation#doTransform
at ForEach.<anonymous> (/app/packages/cli/node_modules/barnard59-core/lib/Pipeline.js:60:23)
at ForEach.emit (events.js:323:22)
at ForEach.EventEmitter.emit (domain.js:482:12)
at errorOrDestroy (/app/packages/cli/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
at onwriteError (/app/packages/cli/node_modules/readable-stream/lib/_stream_writable.js:430:5)
at onwrite …
```
=> fix(cli): throw explicit error message on S3 getObject error

packages/cli/package-lock.json, packages/cli/package.json
Related to: https://github.com/zazuko/barnard59-graph-store/issues/7
=> Upgrade barnard59-graph-store

packages/cli/pipelines/to-stdout.ttl
=> fix(cli): stdout output

api/lib/data-cube/project/index.ts, api/lib/data-cube/table/createDimensionTable.ts, api/lib/data-cube/table/index.ts, api/lib/domain/project/__snapshots__/createDimensionTable.spec.ts.snap, api/lib/domain/project/createDimensionTable.spec.ts, api/lib/domain/project/createDimensionTable.ts, api/lib/domain/table/index.spec.ts, api/lib/domain/table/index.ts, api/test/DimensionTable/AddDimensionAttribute.hydra, api/test/DimensionTable/CsvwMapping/SetsReferencedValueUrl.hydra
=> fix: must. slugify. table. name

api/package-lock.json, api/package.json
re tpluscode/sparql-builder#12
=> fix(api): remove empty INSERT from DELETE, which would fail in Stardog

api/lib/handlers/update-source.ts, api/lib/read-graphs/project.ts, api/lib/read-graphs/table/eventHandlers.ts
correctly replace the values when doing DELETE/INSERT
fixes #272
=> fix(api): project would have two names when updating

api/package-lock.json, api/package.json, docker-compose.yml, packages/rdfine-data-cube/package-lock.json, packages/rdfine-data-cube/package.json
I have no idea why jest tests stopped working but newer babel seems to do the trick
=> build: update babel

api/package-lock.json, api/package.json, packages/cli/package-lock.json, packages/cli/package.json
Update CSVW parser to fix the BOM parsing problem.
Looks like this need a dependency update also in `barnard59-formats`.
=> fix(cli): handle csvs with BOM

k8s/deployment.yaml, k8s/ingress.yaml, k8s/kustomization.yaml, k8s/service.yaml
I've also ran prettier in the k8s YAML manifests, so there is two commits there
=> Setup auth in k8s deployment

k8s/deployment.yaml
Also fixed it live so it works on datacube.zzk.org
=> Small deployment variable fix

api/lib/read-graphs/attribute/eventHandlers.ts
=> Ensure datatype params get deleted with attribute
