- ui/src/components/IdentifierTemplateInput.vue
- ui/src/components/project/TableAdvancedForm.vue
- ui/src/components/project/TableForm.vue
This is a first attempt at improving the "identifier template" input with:
- Clearer placeholder
- Auto-fill once table name is provided
- Auto-complete on column names between "{" and "}"
It is far from perfect. A better solution will probably have to include an actual parser to improve the auto-complete and add column validation.
Fixes #164
> feat(ui): auto-complete identifier template columns

- ui/src/components/PropertyField.vue
- ui/src/components/project/ReferenceAttributeForm.vue
1. The property field was not auto-populated when selecting the table because of the new property field behavior.
2. We should also hide the "columns mapping" section when there are no columns in the identifier.
> fix(ui): regression in reference attr. form

- api/lib/data-cube/table/attributes/addReferenceAttribute.ts
- api/lib/data-cube/table/attributes/addValueAttribute.ts
- api/lib/read-graphs/attribute.ts
- api/lib/read-model/Table/Attribute.ts
- api/lib/read-model/Table/index.ts
- api/lib/services/csvwBuilder.spec-graphs.ts
- api/lib/services/csvwBuilder.spec.ts
- api/lib/services/csvwBuilder.ts
- api/lib/storage/repository/attributes.ts
- api/test/Attribute/DeleteValueAttribute.hydra
- api/test/DimensionTable/CsvwMapping/SetsReferencedValueUrl.hydra
Query to migrate the `READ_MODEL` store. Already fired on the staging environment
```sparql
PREFIX dataCube: <https://rdf-cube-curation.described.at/> 
DELETE
{
?attr rdf:predicate ?predicate .
}
INSERT
{
?attr dataCube:propertyTemplate ?pStr .
}
WHERE
{
?attr a dataCube:Attribute ;
rdf:predicate ?predicate .
BIND (str(?predicate) as ?pStr)
}
```
> fix: replace rdf:predicate with property template completely

- api/hydra/projects.ttl
- ui/src/router.ts
- ui/src/store/common.ts
- ui/src/store/modules/projects.ts
- ui/src/views/Project.vue
- ui/src/views/Projects.vue
- ui/src/views/project/Settings.vue
Project settings are now managed in a tab instead of a modal window. This will be better when we add metadata and more settings. It also makes sense to be able to edit a project directly from the project page.
> feat(ui): add project settings tab

- api/hydra/attributes.ttl
- api/lib/data-cube/table/attributes/Commands.ts
- api/lib/domain/attribute/events.ts
- api/lib/domain/attribute/index.ts
- api/lib/domain/table/__snapshots__/addValueAttribute.spec.ts.snap
- api/lib/domain/table/addValueAttribute.ts
- api/lib/read-graphs/attribute/eventHandlers.ts
- api/lib/read-model/Table/Attribute.ts
- api/lib/read-model/Table/index.ts
- api/lib/services/__snapshots__/csvwBuilder.spec.ts.snap
- api/lib/services/csvwBuilder.spec-graphs.ts
- api/lib/services/csvwBuilder.spec.ts
- api/lib/services/csvwBuilder.ts
- api/lib/services/csvwBuilder/Column.ts
- api/lib/services/csvwBuilder/index.ts
- api/lib/services/csvwBuilder/referenceAttribute.ts
- api/lib/services/csvwBuilder/valueAttribute.ts
- api/package-lock.json
- api/package.json
- api/test/FactTable/CsvwMapping/MapsDatatypeParamsToCsvwTerms.hydra
> fix(csvw): datatype structure as defined in spec

- api/lib/read-model/Project.ts
- api/lib/read-model/Source.ts
- api/lib/read-model/Table/Attribute.ts
- api/lib/read-model/Table/Column.ts
- api/lib/read-model/Table/ColumnMapping.ts
- api/lib/read-model/Table/Table.ts
- api/lib/read-model/Table/index.ts
- api/lib/read-model/index.ts
- api/lib/read-model/wireUp.ts
- api/lib/services/__snapshots__/csvwBuilder.spec.ts.snap
- api/lib/services/csvwBuilder.spec.ts
- api/lib/services/csvwBuilder.ts
- api/lib/services/csvwBuilder/Csvw.ts
- api/lib/services/csvwBuilder/index.ts
Adding the `csvw:url` property which is necessary to match the input files being processed with a table's mapping
> fix: csvw document does not include the url property

- api/lib/domain/project/createSource.spec.ts
- api/lib/domain/project/createSource.ts
As discussed with @ktk, the API will immediately reject CSV where a column is empty (or all-whitespace)
> feat: fail when a csv has empty column names

- api/lib/read-graphs/table/csvw.ts
fixes #203
The referenced column mapping was not being retrieved which caused a missing link between the `?attribute` and `?referencedColumn` in the in-memory graph.
This id fixed by also `DESCRIBing` the blank node which sits in-between.
> fix: column mapping link was not retrieved from the graph

- ui/package-lock.json
- ui/package.json
- ui/src/components/DataTypeField.vue
- ui/src/main.ts
- ui/src/styles/multiselect.css
- ui/src/styles/variables.css
Replace Bulma's autocomplete with a more appropriate vue-multiselect.
If the behavior works well, I will probably replace some other select boxes with it in the UI as well.
Fixes #204
> fix(ui): improve datatype select box

- ui/src/views/Project.vue
Since we need a project's URI to use the CLI, it probably makes sense to offer a way to get it.
This adds a field that displays the project's URI and a button to copy it to the clipboard (Github-like).
> feat(ui): add a way to get a project's URI

- api/lib/express.ts
When there is a class with expected type URIs, we might reflect on all subjects in the request and find ones with the @type
> fix: request model was not being correctly determined

- ui/src/App.vue
- ui/src/components/project/SourceItem.vue
- ui/src/components/project/TableItem.vue
In some cases, the loader would get stuck when an API error occurred.
The error message would also show up *under* the modal.
Fix #234
> fix(ui): infinite loader on API error

- ui/src/components/IdentifierTemplateField.vue
It seems like the implementation of pattern validation in Firefox is less efficient than in Chrome and crashes the app when we abuse it with a long pattern and a long input.
I switched to a manual validation... which is probably a better solution in the end. Although it has the downside of not preventing you from submitting the form. It is not really an issue because the error message that comes back from the API is pretty clear as well.
We should look into a proper validation library (e.g. vee-validate) at some point.
Fixes #228
> fix(ui): issue with native form validation pattern on Firefox

- ui/src/components/project/ReferenceAttributeForm.vue
I got a confused by the wording and formatting on this screen. *Shall* didn't look appropriate because we describe an intent, not a requirement. *Columns* was in plural form although there's only one column. Finally, the `<code>` formatting was giving the impression that in `foo/{bar}`, we would replace `bar` with something, while what we're really replacing is `{bar}`.
Here's an 'after' screenshot:
There's something else I noticed on this screen but didn't change because I don't know in which direction to: *the **category table*** refers to a *dimension* table.
> Clarify ReferenceAttributeForm wording and formatting

- ui/src/datatypes.ts
I got confused when I tried to set the type of a column to `xsd:dateTime`, the suggestions usually show xsd types I am familiar with (eg. `dateTimeStamp`) but instead of `dateTime` it shows `datetime`.
According to [this](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#datatypes), `datetime` is defined as an alias for `dateTime`. The [CSVW Namespace Vocabulary](https://www.w3.org/ns/csvw#term-definitions) seems to confirm that both point to `xsd:dateTime`.
IMO displaying `dateTime` instead of `datetime` would be less confusing to people who are familiar with xsd datatypes but aren't familiar with CSVW aliases.
> Replace csvw:datetime with csvw:dateTime

- packages/cli/lib/s3.ts
- packages/cli/package-lock.json
- packages/cli/package.json
I debugged this locally and the whole body was loaded in memory. AWS SDK provides a way of directly streaming the request.
Error reporting is also a tiny bit better.
> S3 getObject streams directly instead of loading whole body

- Dockerfile
- ui/package-lock.json
- ui/package.json
- ui/src/api/index.ts
Use relative URL for API in production to avoid needing a specific build per deployment.
Fixes #89 
Requires a fix in Alcaeus to support relative URLs.
> fix(ui): use relative API URL in docker image

- packages/cli/index.ts
- packages/cli/lib/commands/transform.ts
- packages/cli/lib/datacube-metadata.ts
- packages/cli/lib/project.ts
- packages/cli/lib/s3.ts
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/pipelines/datacube-metadata.ttl
- packages/cli/pipelines/from-filesystem.ttl
- packages/cli/pipelines/from-s3.ttl
- packages/cli/pipelines/main.ttl
- packages/cli/typings/barnard59-core/lib/Pipeline.d.ts
Tries to find a file called `datacube-metadata.ttl` (either in S3 or filesystem, depending on the CLI options). Imports metadata from it and links everything together (DataSet -> Structure -> Components, DataSet -> Observations).
If the metadata file is not found, it will still generate the minimum viable metadata (DataSet, Structure, linked Observations) so that the data can be used. It won't generate a valid datacube that can be used in the visualization tool though.
The metadata file should look like the following:
```turtle
@base <http://ld.zazuko.com/blw/> .
@prefix qb: <http://purl.org/linked-data/cube#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix scale: <http://ns.bergnet.org/cube/scale/> .
@prefix schema: …
```
> Load datacube metadata

- .github/workflows/cli-docker.yml
- packages/cli/lib/datacube-metadata.ts
I noticed that the CLI docker image build would fail so I added a GitHub actions workflow.
Master excluded, because that is going to be built by docker hub anyway
> ci(cli): added workflow to build CLI on github action

- ui/src/components/project/SourceItem.vue
- ui/src/views/project/Sources.vue
It will make everything a bit more janky, but it should still feel a bit faster since we have to load all the tables one by one and then all the attributes for each of them.
> fix(ui): show sources before tables are loaded

- api/package-lock.json
- api/package.json
We've already been in the clear but this patches a potential vulnerability [GHSA-6g6m-m6h5-w9gf](https://github.com/advisories/GHSA-6g6m-m6h5-w9gf)
> build(deps): update express-jwt

- api/frontend.ts
- ui/src/api/index.ts
- ui/src/store/modules/oidc.ts
- ui/types/global.d.ts
This does two things ; two commits which can be split in two PRs if needed:
- ensure all API calls are authenticated in the UI
- make the whole oidc-client config runtime-configurable to support setup with Auth0 and Dex
> Fix API authentication in UI & make the OIDC config runtime-configurable

- packages/cli/index.ts
- packages/cli/lib/auth.ts
- packages/cli/lib/commands/transform.ts
- packages/cli/lib/project.ts
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/rdfine-data-cube/package-lock.json
This makes the CLI authenticate using the `client_credentials` grant.
This adds 4 flags, to specify the IdP, the client id/secret as well as arbitrary params added to the token request. This is useful when working with providers like Auth0, who need additional params to get proper JWT tokens
Because the access token can be short-lived (5min by default on Keycloak), I needed to have a renew mechanism. It is based on `setInterval`, because the `Hydra.defaultHeaders` method isn't async (maybe that could be a thing @tpluscode?)
Not sure how I'm supposed to test a pipeline, but locally I was able to run it without having 401 errors popping in the logs
> Authenticate API calls in CLI

- packages/cli/lib/auth.ts
- packages/cli/lib/commands/transform.ts
> refactor: use async function to set auth headers

- api/frontend.ts
The `/env-config.js` endpoint called `res.end` even though we were piping a stream, which broke everything. This does not impact simple setups (like all our production ones) but it prevents the app from working with providers like dex.
> Fix the AUTH_CONFIG_FILE not being read

- ui/src/store/modules/oidc.ts
Enabling opt-in setting of `vuex-oidc` to automatically renew auth tokens.
> fix: ui should automatically renew auth token
